### ISSUE TITLE
[ExplorePage] 패키지 lazy loading

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2022-01-fe-air-tour#13]
## TODO
- [x] lazy loading 구현
- [x] 여러 개의 컴포넌트 하드코딩 -> map()으로 refactor
- [x] json 데이터 불러오기
