### ISSUE TITLE
[MainPage] 긴급 모객 패키지 슬라이드 구현

### ISSUE THREAD

**Issue by yeonsu0-0** [GDSC-SWU/2022-01-fe-air-tour#2]
## TODO

- [x] 슬라이드 버튼 구현
- [x] card간 간격 이슈 해결
- [ ] 데이터 json으로 변경

**Comment by yeonsu0-0** [comment]
## TODO

- [ ] 데이터 json으로 변경
